name: mvp_emprendimiento
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  permission_handler: ^11.0.0
  flutter_image_compress: ^2.0.4


  # Firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14

  # Get
  get: ^4.6.5
  get_storage: ^2.1.1
  
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

